import { mkdir, readdir, readFile, rm, writeFile, copyFile } from 'fs/promises';
import path from 'path';
import { marked } from 'marked';

const ROOT = path.resolve('.');
const DIST = path.join(ROOT, 'dist');
const ASSETS_SRC = path.join(ROOT, 'assets');
const IGNORED = new Set(['.git', 'node_modules', 'dist', '.github']);

async function scanDirectory(currentDir, relativePath = '') {
  const entries = await readdir(currentDir, { withFileTypes: true });
  const nodes = [];

  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    if (IGNORED.has(entry.name) || entry.name.startsWith('.')) {
      continue;
    }

    const entryRel = relativePath ? path.posix.join(relativePath, entry.name) : entry.name;
    const entryPath = path.join(currentDir, entry.name);

    if (entry.isDirectory()) {
      const children = await scanDirectory(entryPath, entryRel);
      if (children.length > 0) {
        nodes.push({ name: entry.name, type: 'dir', path: entryRel, children });
      }
    } else if (entry.isFile() && entry.name.toLowerCase().endsWith('.md')) {
      const markdown = await readFile(entryPath, 'utf8');
      const title = extractTitle(markdown, entry.name);
      const excerpt = extractExcerpt(markdown);
      const htmlPath = `${entryRel.slice(0, -3)}.html`;
      nodes.push({ name: entry.name, type: 'file', sourcePath: entryRel, htmlPath, title, excerpt });
    }
  }

  return nodes;
}

function extractTitle(markdown, filename) {
  const headingMatch = markdown.match(/^#{1,3}\s+(.+)$/m);
  if (headingMatch) {
    return headingMatch[1].trim();
  }
  return filename.replace(/\.md$/i, '').replace(/[-_]/g, ' ');
}

function extractExcerpt(markdown) {
  const clean = markdown.replace(/```[\s\S]*?```/g, ' ').replace(/[#>*`~\-\[\]]/g, ' ');
  const excerpt = clean.replace(/\s+/g, ' ').trim();
  return excerpt.length > 160 ? `${excerpt.slice(0, 157)}...` : excerpt;
}

function flattenDocs(nodes) {
  const docs = [];
  for (const node of nodes) {
    if (node.type === 'file') {
      docs.push(node);
    } else if (node.type === 'dir') {
      docs.push(...flattenDocs(node.children));
    }
  }
  return docs;
}

function getAssetPrefix(pagePath) {
  if (!pagePath) return '';
  const depth = pagePath.split('/').length - 1;
  return '../'.repeat(depth);
}

function escapeHtml(value) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function renderPage({ title, bodyHtml, tree, docs, currentHtmlPath, assetPrefix }) {
  const serialized = JSON.stringify({ tree, docs });
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)} - Galactic Hub Docs</title>
  <link rel="stylesheet" href="${assetPrefix}assets/style.css">
</head>
<body>
  <div class="frame">
    <aside class="sidebar">
      <div class="branding">
        <strong>Galactic Hub</strong>
        <p>Static docs explorer</p>
      </div>
      <div class="search-container">
        <label for="site-search">Search docs</label>
        <input id="site-search" type="search" placeholder="Search by title or content">
      </div>
      <nav class="tree" id="file-tree" aria-label="Document tree"></nav>
    </aside>
    <main class="content">
      <header class="page-header">
        <h1>${escapeHtml(title)}</h1>
        <p class="page-meta">Browse converted Markdown content from the repository.</p>
      </header>
      <article class="doc-content">
        ${bodyHtml}
      </article>
    </main>
  </div>
  <script>window.SITE_DATA = ${serialized}; window.CURRENT_HTML_PATH = ${JSON.stringify(currentHtmlPath)}; window.ROOT_PREFIX = ${JSON.stringify(assetPrefix)};</script>
  <script type="module" src="${assetPrefix}assets/app.js"></script>
</body>
</html>`;
}

function renderIndex({ tree, docs, assetPrefix }) {
  const serialized = JSON.stringify({ tree, docs });
  const title = 'Documentation Explorer';
  const bodyHtml = `
    <section class="home-intro">
      <p>Welcome to the autogenerated Galactic Hub documentation explorer. Use the search box or the file tree to open Markdown pages.</p>
      <div class="home-summary">
        <strong>${docs.length}</strong> Markdown files discovered across the repository.
      </div>
    </section>
  `;

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)} - Galactic Hub Docs</title>
  <link rel="stylesheet" href="${assetPrefix}assets/style.css">
</head>
<body>
  <div class="frame">
    <aside class="sidebar">
      <div class="branding">
        <strong>Galactic Hub</strong>
        <p>Static docs explorer</p>
      </div>
      <div class="search-container">
        <label for="site-search">Search docs</label>
        <input id="site-search" type="search" placeholder="Search by title or content">
      </div>
      <nav class="tree" id="file-tree" aria-label="Document tree"></nav>
    </aside>
    <main class="content">
      <header class="page-header">
        <h1>${escapeHtml(title)}</h1>
        <p class="page-meta">Generated from repository Markdown sources.</p>
      </header>
      <article class="doc-content">
        ${bodyHtml}
      </article>
    </main>
  </div>
  <script>window.SITE_DATA = ${serialized}; window.CURRENT_HTML_PATH = ${JSON.stringify('index.html')}; window.ROOT_PREFIX = ${JSON.stringify(assetPrefix)};</script>
  <script type="module" src="${assetPrefix}assets/app.js"></script>
</body>
</html>`;
}

async function copyAssets() {
  const target = path.join(DIST, 'assets');
  await mkdir(target, { recursive: true });
  await copyFile(path.join(ASSETS_SRC, 'app.js'), path.join(target, 'app.js'));
  await copyFile(path.join(ASSETS_SRC, 'style.css'), path.join(target, 'style.css'));
}

async function build() {
  console.log('Building documentation explorer...');
  await rm(DIST, { recursive: true, force: true });
  await mkdir(DIST, { recursive: true });
  await writeFile(path.join(DIST, '.nojekyll'), '', 'utf8');
  await copyAssets();

  const tree = await scanDirectory(ROOT, '');
  const docs = flattenDocs(tree);

  await writeFile(path.join(DIST, 'index.html'), renderIndex({ tree, docs, assetPrefix: '' }), 'utf8');

  for (const doc of docs) {
    const markdown = await readFile(path.join(ROOT, doc.sourcePath), 'utf8');
    const bodyHtml = marked.parse(markdown);
    const assetPrefix = getAssetPrefix(doc.htmlPath);
    const pageHtml = renderPage({ title: doc.title, bodyHtml, tree, docs, currentHtmlPath: doc.htmlPath, assetPrefix });
    const outputFile = path.join(DIST, doc.htmlPath);
    await mkdir(path.dirname(outputFile), { recursive: true });
    await writeFile(outputFile, pageHtml, 'utf8');
  }

  console.log(`Generated ${docs.length} page(s) into dist/`);
}

build().catch((error) => {
  console.error(error);
  process.exit(1);
});
